<?php

$textTranslate = [
    "en" => [
        "sources" => "sources",
        "author" => "author",
        "contact" => "contact",
        "translator" => "translator",
        "translate" => "translate",
        "orTranslateMorseCode" => "Or translate Morse code (-/./space)",
        "enterTheTextToBeTranslatedIntoMorseCode" => "Enter the text to be translated into Morse code",
        "minimum" => "minimum",
        "maximum" => "maximum",
    ],
    "pl" => [
        "sources" => "źródła",
        "author" => "autor",
        "contact" => "kontakt",
        "translator" => "tłumacz",
        "translate" => "przetłumacz",
        "orTranslateMorseCode" => "Lub przetłumacz kod Morse'a (-/./spacja)",
        "enterTheTextToBeTranslatedIntoMorseCode" => "Wprowadź tekst do tłumaczenia na kod Morse'a",
        "minimum" => "minimum",
        "maximum" => "maksimum",
    ],
    "esperanto" => [
        "sources" => "fonto",
        "author" => "aŭtoro",
        "contact" => "kontakto",
        "translator" => "tradukisto",
        "translate" => "traduki",
        "orTranslateMorseCode" => "Aŭ traduki kodo Morse (-/./spaco)",
        "enterTheTextToBeTranslatedIntoMorseCode" => "Enigu tekston traduki kodon Morsea",
        "minimum" => "minimumajn",
        "maximum" => "maksimuma",
    ],
    "fr" => [
        "sources" => "source",
        "author" => "auteur",
        "contact" => "contact",
        "translator" => "traducteur",
        "translate" => "traduire",
        "orTranslateMorseCode" => "Ou traduire le code Morse (-/./espace)",
        "enterTheTextToBeTranslatedIntoMorseCode" => "Entrez le texte à traduire le code Morsea",
        "minimum" => "minimum",
        "maximum" => "maximum",
    ]
];

$morseCode = [
    "a" => ".-",
    "b" => "-...",
    "c" => "-.-.",
    "d" => "-..",
    "e" => ".",
    "f" => "..-.",
    "g" => "--.",
    "h" => "....",
    "i" => "..",
    "j" => ".---",
    "k" => "-.-", // or invitation to transmit
    "l" => ".-..",
    "m" => "--",
    "n" => "-.",
    "o" => "---",
    "p" => ".--.",
    "q" => "--.-",
    "r" => ".-.",
    "s" => "...",
    "t" => "-",
    "u" => "..-",
    "v" => "...-",
    "w" => ".--",
    "x" => "-..-",
    "y" => "-.--",
    "z" => "--..",
    "ą" => ".-.-",
    "ć" => "-.-..",
    "ę" => "..-..",
    "ch" => "----",
    "ł" => ".-..-", // or [STOP]
    "ń" => "--.--",
    "ó" => "---.",
    "ś" => "...-...",
    "ż" => "--..-.",
    "ź" => "--..-",
    "1" => ".----",  // short version .-       
    "2" => "..---",  // short version ..-
    "3" => "...--",  // short version ...-
    "4" => "....-",  // short version ....-
    "5" => ".....",  // short version .....
    "6" => "-....",  // short version -....
    "7" => "--...",  // short version -...
    "8" => "---..",  // short version -..
    "9" => "----.",  // short version -.
    "0" => "-----",  // short version -
    "." => ".-.-.-", 
    "," => "--..--",
    "'" => ".----.",
    "\"" => ".-..-.",
    "_" => "..--.-",
    ":" => "---...",    
    ";" => "-.-.-.",
    "?" => "..--..", // or repeat please
    "!" => "-.-.--", // or --..--
    "-" => "-....-",
    "+" => ".-.-.", // or end of transmit
    "/" => "-..-.",
    "(" => "-.--.", 
    ")" => "-.--.-", 
    "=" => "-...-",
    "@" => ".--.-.", 
    "$" => "...-..-",
    "[SOS]" => "...---...",
    "[end of work]" => "...-.-", 
    "[wait]" => ".-...", 
    "[understood]" => "...-.", 
    "[error]" => "........", 
    "[starting signal]" => "-.-.-", 
    "[start of work (VVV)]" => "...-...-...-", 
];
